require "localuser"
local user = vim.api.nvim_get_var("LOCALUSER")
require(user .. ".local")
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.treesitter-context"
require "user.trouble"
require "user.aerial"
require "user.autopairs"
require "user.surround"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.scope"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha" -- dashboard
-- require "user.dashboard" -- dashboard
require "user.whichkey"
require "user.autocommands"
require "user.norg"
require "user.mdeval"
require "user.twilight"
require "user.zen"
require "user.neogen"
require "user.smart-splits"
require "user.telescope-file-browser"

