################################################################################
#                                                                              #
# Environment                                                                  #
#                                                                              #
################################################################################
source "$ZDOTDIR/local/zuser"
export ZLOCAL="$ZDOTDIR/local/$ZUSER/zshenv"
source "$ZLOCAL"
################################################################################
#                                                                              #
# Aliases                                                                      #
#                                                                              #
################################################################################
source "$ALIASES"
################################################################################
#                                                                              #
# Options                                                                      #
#                                                                              #
################################################################################
# Turn off all beeps
unsetopt BEEP
# Turn off autocomplete beeps
# unsetopt LIST_BEEP
bindkey -e  # emacs mode
################################################################################
#                                                                              #
# Completion                                                                   #
#                                                                              #
################################################################################
declare -A compsources
compsources=(
  [_conda]='https://raw.githubusercontent.com/esc/conda-zsh-completion/master/_conda'
  [_docker]='https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker'
  [_docker-compose]='https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/zsh/_docker-compose'
)
for compsrc comprepo in ${(kv)compsources}; do
  [ ! -f $ZCOMP/$compsrc ] && curl -L $comprepo -o $ZCOMP/$compsrc
done
fpath=($ZCOMP/ $fpath)
## menu-style
zstyle ':completion:*' menu select
autoload -Uz compinit && compinit -i
zstyle ':completion:*' special-dirs true
# case insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# Tab completion colors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# add new installed packages into completions
zstyle ':completion:*' rehash true
# Use better completion for the kill command
#zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;34'
#zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
# use completion cache
zstyle ':completion::complete:*' use-cache true
# for docker
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
################################################################################
#                                                                              #
# Prompt - Minimal                                                             #
#                                                                              #
################################################################################
# PROMPT='%b%F{#0b98de}%~ %f
# %? %F{#fd9014}%(!.#.>) %f'
# autoload -Uz vcs_info
# precmd_vcs_info() { vcs_info }
# precmd_functions+=( precmd_vcs_info )
#
# zstyle ':vcs_info:*' enable git
# zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:*' stagedstr '%F{yellow}●%f'
# zstyle ':vcs_info:*' unstagedstr '%F{red}●%f'
# zstyle ':vcs_info:git:*' formats '[%F{green}%b%f%c%u]'
# zstyle ':vcs_info:git:*' actionformats '[%F{cyan}%b (%a)%f%c%u]'
#
# RPROMPT='$vcs_info_msg_0_'

################################################################################
#                                                                              #
# Prompt - Powerlevel10k                                                       #
#                                                                              #
################################################################################
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$POWERLEVEL10K/powerlevel10k.zsh-theme"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
################################################################################
#                                                                              #
# Plugins                                                                      #
#                                                                              #
################################################################################
#auto suggestions
autosugestions_dir="$ZPLUG/zsh-autosuggestions" 
autosugestions="$autosugestions_dir/zsh-autosuggestions.zsh" 
[ ! -f "$autosugestions" ] && \
  git clone https://github.com/zsh-users/zsh-autosuggestions.git "$autosugestions_dir"
source "$autosugestions"
set ZSH_AUTOSUGGEST_USE_ASYNC=true
#fast syntax highlighting
syntax_dir="$ZPLUG/fast-syntax-highlighting"
syntax="$syntax_dir/fast-syntax-highlighting.plugin.zsh"
[ ! -f "$syntax" ] && \
  git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git "$syntax_dir"
source "$syntax"
# z command
zcmd_dir="$ZPLUG/zsh-z"
zcmd="$zcmd_dir/zsh-z.plugin.zsh"
[ ! -f "$zcmd" ] && \
  git clone https://github.com/agkozak/zsh-z.git "$zcmd_dir"
source "$zcmd"
# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### WEB LLM
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh
