path+=("$HOME/.bin/nvim_appimage/usr/bin/")
path+=("$HOME/.local/bin")

export EDITOR="nvim"

export WHOME="/mnt/c/Users/NicolasScottoDiPerto/"
export WEZTERM_CONFIG_DIR="$WHOME"
export WEZTERM_CONFIG_FILE="$WEZTERM_CONFIG_DIR/.wezterm.lua"

# These 2 are for X forwarding on wsl
export DISPLAY=$(ip route list default | awk '{print $3}'):0
# export DISPLAY=$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0
export LIBGL_ALWAYS_INDIRECT=1

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm


export GOROOT="/usr/local/go"
path+=("$GOROOT/bin")

alias c="cd $WHOME"
alias e="explorer.exe"

export path

export TVM_HOME=$WHOME/Work/tvm
export PYTHONPATH=$TVM_HOME/python:$PYTHONPATH




# REMOTE
export BOO=10.11.83.36
